version: '3'

services:
  postgres:
    image: "postgres"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - pgsql-env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} psql -U $${POSTGRES_USER} -h $${POSTGRES_HOST} --command 'select 1;' && return 0"]
      interval: 1s
      timeout: 5s
      retries: 5
  lemur:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - lemur-env
      - pgsql-env
    volumes:
      - type: bind
        source: ./lemur.conf.py
        target: /home/lemur/.lemur/lemur.conf.py
        read_only: true
    ports:
      - 87:80
      - 447:443
  redis:
    image: "redis:latest"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING"]
      interval: 1s
      timeout: 5s
      retries: 5
volumes:
    pg_data: {}
