version: '3'

services:
  postgres:
    image: "postgres"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - pgsql-env
    ports:
      - 5432:5432
  lemur:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - lemur-env
      - pgsql-env
    volumes:
      - ./lemur.conf.py:/home/lemur/.lemur/lemur.conf.py:ro
    ports:
      - 87:80
      - 447:443
  redis:
    image: "redis:latest"

volumes:
  pg_data: { }
